# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true # Mantém a proteção CSRF ativada por padrão.

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        # name: SYMFONY_SESSION # Opcional: Descomente para dar um nome específico ao seu cookie de sessão (útil para depuração)
        # gc_maxlifetime: 3600 # Opcional: Tempo de vida máximo de uma sessão em segundos (3600s = 1 hora)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file